# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CevaShipmentDetail',
            fields=[
                ('waybill_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ship_date', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_location', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_location', models.CharField(blank=True, max_length=100, null=True)),
                ('total_pcs', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_weight', models.CharField(blank=True, max_length=1000, null=True)),
                ('charge_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('freight_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('service_level', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('history_data', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
