# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceva', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cevashipmentdetail',
            options={},
        ),
    ]
